In [1]:
import numpy as np

In [7]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
arr.mean(0)

array([4.5, 5.5, 6.5])

In [13]:
arr.mean(1)

array([ 1.,  4.,  7., 10.])

In [10]:
# axis = 0 broadcasting
arr - arr.mean(0)

array([[-4.5, -4.5, -4.5],
       [-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5],
       [ 4.5,  4.5,  4.5]])

In [12]:
# axis = 1 broadcasting
arr - arr.mean(1).reshape(4,1)

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

### high demansional

In [20]:
arr_1d = np.random.normal(size=3)
arr_1d

array([-0.2536304 ,  0.55801929, -1.46725796])

In [22]:
arr_1d[:,np.newaxis]

array([[-0.2536304 ],
       [ 0.55801929],
       [-1.46725796]])

In [23]:
arr_1d[:,np.newaxis].shape

(3, 1)

In [24]:
arr_1d[np.newaxis,:]

array([[-0.2536304 ,  0.55801929, -1.46725796]])

In [25]:
_.shape

(1, 3)

In [17]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
arr_3d = arr[:,np.newaxis,:]
arr_3d

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [29]:
a = np.arange(30).reshape((2,3,5))
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [33]:
# empty axis=2
a - np.ones((3,5))

array([[[-1.,  0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12., 13.]],

       [[14., 15., 16., 17., 18.],
        [19., 20., 21., 22., 23.],
        [24., 25., 26., 27., 28.]]])

In [36]:
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [34]:
a - np.ones((2,3,1))

array([[[-1.,  0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12., 13.]],

       [[14., 15., 16., 17., 18.],
        [19., 20., 21., 22., 23.],
        [24., 25., 26., 27., 28.]]])

In [37]:
np.ones((2,1,5))

array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]])

In [35]:
a - np.ones((2,1,5))

array([[[-1.,  0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12., 13.]],

       [[14., 15., 16., 17., 18.],
        [19., 20., 21., 22., 23.],
        [24., 25., 26., 27., 28.]]])

In [41]:
indexer = [slice(None)] * 4
indexer

[slice(None, None, None),
 slice(None, None, None),
 slice(None, None, None),
 slice(None, None, None)]

In [42]:
indexer[2]=np.newaxis
indexer

[slice(None, None, None),
 slice(None, None, None),
 None,
 slice(None, None, None)]