In [1]:
import numpy as np

In [2]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [3]:
3*0.1

0.30000000000000004

In [9]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [8]:
# Create a 8x8 matrix and fill it with a checkerboard pattern
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [7]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [11]:
# Create a checkerboard 8x8 matrix using the tile function
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
# Normalize a 5x5 random matrix
z = np.random.random((5,5))
z = (z - z.mean())/z.std()
z

array([[ 1.12951201, -0.4326709 , -1.29436119, -1.12599538,  1.43502317],
       [ 1.46258817, -0.50588972,  0.04575717, -2.01231586,  0.30045709],
       [-0.79978748,  1.39460041,  0.30580725, -0.97829124,  0.01194403],
       [-0.29434853,  1.48708081,  0.44827533, -1.12953787,  1.30827875],
       [ 0.25428823, -0.20777876, -0.39512766, -1.32822533,  0.92071748]])

In [20]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte, (1,)),
                  ("g", np.ubyte, (1,)),
                  ("b", np.ubyte, (1,)),
                  ("a", np.ubyte, (1,))])
color

dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

In [23]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
np.ones((5,3)).dot(np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [24]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [33]:
Z = np.ones((2,2))
Z**Z
# 2 << Z >> 2 # illegal
Z <- Z
1j*Z
Z/1/1
# Z<Z>Z # illegal

array([[1., 1.],
       [1., 1.]])

In [34]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [39]:
# How to round away from zero a float array ?
Z = np.random.uniform(-10,+10,10)
print(Z)
print(Z.round()) # round method won't work because it's not round away from zero
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 6.1571284   2.37951001  7.6535024  -1.16603364 -3.12722002  8.26997485
  3.56865088 -1.70604804 -0.92407135 -0.24992128]
[ 6.  2.  8. -1. -3.  8.  4. -2. -1. -0.]
[ 7.  3.  8. -2. -4.  9.  4. -2. -1. -1.]


In [41]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1, Z2, np.intersect1d(Z1,Z2))

[9 6 0 4 6 5 2 6 5 0] [6 2 9 2 3 4 8 3 1 6] [2 4 6 9]


In [49]:
# 虚数
np.emath.sqrt(-1)

1j

In [51]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
tomorrow

numpy.datetime64('2020-02-11')

In [54]:
# How to get all the dates corresponding to the month of July 2016? 
d_range = np.arange(np.datetime64('2016-07-01', 'D'), np.datetime64('2016-08-01', 'D'))
d_range = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
d_range

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [77]:
# How to compute ((A+B)*(-A/2)) in place (without copy)?
# the below won't work because A and B were copied
A = np.ones(3)
B = np.ones(3)*2
(A + B) * (A/-2)
A

array([1., 1., 1.])

In [81]:
# below code works: A changed value
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
A

array([-1.5, -1.5, -1.5])

In [113]:
# Extract the integer part of a random array using 5 different methods
np.random.seed(3)
a = np.random.rand(5)*10
print(a)
print(np.floor(a))
print(a // 1)
print(a.astype(int).astype(float))
print (np.ceil(a)-1)
print (np.trunc(a))

[5.50797903 7.08147823 2.90904739 5.10827605 8.92946954]
[5. 7. 2. 5. 8.]
[5. 7. 2. 5. 8.]
[5. 7. 2. 5. 8.]
[5. 7. 2. 5. 8.]
[5. 7. 2. 5. 8.]


In [117]:
Z = np.arange(10)
%timeit np.add.reduce(Z)
%timeit np.sum(Z)

1.48 µs ± 124 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
4.9 µs ± 829 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [119]:
# Consider two random array A and B, check if they are equal
np.allclose(A,B)

False

In [127]:
# Make an array immutable (read-only)
a = np.arange(5)
a.flags.writeable = False
a[2] = 3

ValueError: assignment destination is read-only

In [140]:
# Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2) # radium
T = np.arctan2(Y,X)    # angle in radian
np.c_[R,T]

array([[1.11208683, 0.71267847],
       [0.8105777 , 1.11182441],
       [0.3434145 , 1.15259339],
       [0.97239429, 1.12464758],
       [0.89345156, 1.39786116],
       [1.25793392, 0.88260639],
       [0.42095818, 0.50846975],
       [0.8621084 , 1.2879929 ],
       [1.19163786, 0.62664209],
       [0.56142761, 0.53667985]])

In [149]:
# Create random vector of size 10 and replace the maximum value by 0
b = np.random.rand(10)*10
print(b)
b[b.argmax()] = 0
print(b)

[6.94764977 3.90958016 0.46296203 4.39421533 3.71980312 5.97003242
 1.3421817  2.27712897 8.14782417 2.64325527]
[6.94764977 3.90958016 0.46296203 4.39421533 3.71980312 5.97003242
 1.3421817  2.27712897 0.         2.64325527]


In [155]:
# Create a structured array with x and y coordinates covering the [0,1]x[0,1] area 
np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))

[array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ]]),
 array([[0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.25, 0.25, 0.25, 0.25, 0.25],
        [0.5 , 0.5 , 0.5 , 0.5 , 0.5 ],
        [0.75, 0.75, 0.75, 0.75, 0.75],
        [1.  , 1.  , 1.  , 1.  , 1.  ]])]

In [159]:
# Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
    print(str(dtype))
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(str(dtype))
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

<class 'numpy.int8'>
-128
127
<class 'numpy.int32'>
-2147483648
2147483647
<class 'numpy.int64'>
-9223372036854775808
9223372036854775807
<class 'numpy.float32'>
-3.4028235e+38
3.4028235e+38
1.1920929e-07
<class 'numpy.float64'>
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [172]:
# Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
X = np.arange(3)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(X, Y)
print(np.subtract(X, Y))
print(np.subtract.outer(X, Y))
print(np.linalg.det(C))

[0 1 2] [0.5 1.5 2.5]
[-0.5 -0.5 -0.5]
[[-0.5 -1.5 -2.5]
 [ 0.5 -0.5 -1.5]
 [ 1.5  0.5 -0.5]]
-15.17037037037037


In [178]:
# How to find the closest value (to a given scalar) in a vector?
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

42
