easier way to construct a dictionary

In [1]:
import pandas as pd
import numpy as np

In [1]:
dict((i, i **2) for i in range(5))

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

use itertools combination and permutation loops

In [12]:
import itertools
comb=itertools.combinations([1,2,3],2)
perm=itertools.permutations([1,2,3],2)

In [13]:
for x in comb:
    print(x)

(1, 2)
(1, 3)
(2, 3)


In [14]:
for x in perm:
    print(x)

(1, 2)
(1, 3)
(2, 1)
(2, 3)
(3, 1)
(3, 2)


numpy indexing vs slicing could lead to different dimentional arrays

In [2]:
import numpy as np

In [3]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [4]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [5]:
arr2d[:, 0]

array([1, 4, 7])

use meshgrid

In [6]:
points = np.arange(-3, 3, 1)
points

array([-3, -2, -1,  0,  1,  2])

In [7]:
xs, ys = np.meshgrid(points, np.arange(0.5, 6.5, 1))

In [8]:
xs

array([[-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1,  2]])

In [9]:
ys

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [3.5, 3.5, 3.5, 3.5, 3.5, 3.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [5.5, 5.5, 5.5, 5.5, 5.5, 5.5]])

linalg for inverse and qr decomposition(上下矩阵)

In [4]:
import numpy as np
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
X

array([[-1.66651076,  0.14493227,  1.66425065, -0.74280538,  1.82229064],
       [ 0.68556317,  0.58185064,  0.26198194,  0.71682287, -0.68011223],
       [-0.62608062, -0.3836518 , -0.13972166, -0.56409402,  0.40683895],
       [ 1.39174064, -0.57408442, -0.35954896,  1.55975894,  0.93630278],
       [-1.12227941, -0.31641404, -3.2747385 ,  0.77338947,  0.63051815]])

In [5]:
mat = X.T.dot(X)
mat

array([[ 6.835685  , -0.04631051,  0.66836326,  3.3853097 , -3.16236775],
       [-0.04631051,  0.93643499,  1.68982715, -0.61430153, -1.02472114],
       [ 0.66836326,  1.68982715, 13.71107458, -4.06306154,  0.39629829],
       [ 3.3853097 , -0.61430153, -4.06306154,  4.41477618, -0.12257999],
       [-3.16236775, -1.02472114,  0.39629829, -0.12257999,  5.22302979]])

In [6]:
inv(mat)

array([[  83.32112877,  108.73017419,  -45.95933596,  -89.02833423,
          73.17796142],
       [ 108.73017419,  143.87613358,  -60.21064584, -116.10683651,
          95.90347618],
       [ -45.95933596,  -60.21064584,   25.47925704,   49.19125601,
         -40.4184878 ],
       [ -89.02833423, -116.10683651,   49.19125601,   95.44045071,
         -78.17546528],
       [  73.17796142,   95.90347618,  -40.4184878 ,  -78.17546528,
          64.54586477]])

In [8]:
mat@inv(mat)

array([[ 1.00000000e+00, -1.10149773e-14,  9.07322624e-15,
         4.33593397e-15,  3.88595336e-15],
       [-3.93555694e-16,  1.00000000e+00,  8.94502468e-15,
        -5.22336523e-15,  1.54669413e-14],
       [-5.22068222e-14, -9.44725356e-14,  1.00000000e+00,
         6.14318913e-14, -7.93056007e-14],
       [ 1.33812507e-16, -5.94372421e-14, -2.19743619e-15,
         1.00000000e+00,  4.01747280e-14],
       [ 2.28616841e-15, -1.69634272e-13, -1.51834436e-14,
         2.29900649e-14,  1.00000000e+00]])

In [13]:
q,r=qr(mat)
q

array([[-0.82509698,  0.1055599 , -0.25169607,  0.20583515,  0.4498367 ],
       [ 0.00558988, -0.41492418,  0.39645001, -0.56840445,  0.5895341 ],
       [-0.08067436, -0.73938643, -0.60445847, -0.14034766, -0.24845895],
       [-0.40862164,  0.31394176,  0.03263289, -0.70885036, -0.48055716],
       [ 0.38171158,  0.41405713, -0.64268307, -0.33523421,  0.39677381]])

In [14]:
r

array([[-8.28470489e+00, -2.33011523e-01,  1.63375767e-01,
        -4.31962108e+00,  4.61534068e+00],
       [ 0.00000000e+00, -2.26002132e+00, -1.18798548e+01,
         4.95164156e+00,  1.92249455e+00],
       [ 0.00000000e+00,  0.00000000e+00, -8.17335123e+00,
         1.58318997e+00, -3.21059402e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.47209402e+00, -1.78813731e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  6.14716087e-03]])

random walk

In [29]:
import random
random.randint(0, 1)

1

In [40]:
nsteps = 1000
nwalks = 5000
draws = np.random.randint(0, 2, size=(nwalks,nsteps))
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)

In [43]:
walks.shape

(5000, 1000)

In [47]:
walks.max()

114

In [48]:
walks.min()

-119

In [50]:
(abs(walks)>=30).any(1)

array([ True,  True,  True, ..., False,  True,  True])

In [51]:
_.sum()

3395

In [52]:
crossing_ct=(abs(walks)>=30).argmax(1)

In [54]:
crossing_ct

array([593, 489, 499, ...,   0, 749, 351], dtype=int64)

In [1]:
import pandas_datareader.data as web

ModuleNotFoundError: No module named 'pandas_datareader'

In [6]:
import pandas as pd
import numpy as np
pd.DataFrame(np.arange(5*4).reshape(5,4))

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

Regular Expression

In [38]:
#\t=<tab>, \n=<enter>
text = "foo bar\t baz \tqux"
print(text)

foo bar	 baz 	qux


In [13]:
import re

In [49]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = '([A-Z0-9._%+-]+)@([A-Z0-9.-]+).([A-Z]{2,4})'

In [50]:
regex = re.compile(pattern, flags=re.IGNORECASE)
regex.findall(text)

[('dave', 'google.', 'om'),
 ('steve', 'gmail.', 'om'),
 ('rob', 'gmail.', 'om'),
 ('ryan', 'yahoo.', 'om')]

Hierachical Indexing

In [21]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
    index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
    columns=[['Ohio', 'Ohio', 'Colorado'], ['Green', 'Blue', 'Green']])
frame.columns.names = ['state', 'color']

In [22]:
frame

state  Ohio      Colorado
color Green Blue    Green
a 1       0    1        2
  2       3    4        5
b 1       6    7        8
  2       9   10       11

In [24]:
frame.sort_index(level=1)

state  Ohio      Colorado
color Green Blue    Green
a 1       0    1        2
b 1       6    7        8
a 2       3    4        5
b 2       9   10       11

In [23]:
frame.sum(level = 0)

state  Ohio      Colorado
color Green Blue    Green
a         3    5        7
b        15   17       19

In [26]:
frame.sum(level = 'state',axis=1)

state  Ohio  Colorado
a 1       1         2
  2       7         5
b 1      13         8
  2      19        11

In [3]:
# data merge, join, combine
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan], index=['f', 'e', 'd', 'c', 'b', 'a'])
b = pd.Series(np.arange(len(a), dtype=np.float64),index=['f', 'e', 'd', 'c', 'b', 'a'])
b[-1] = np.nan

In [4]:
b[:-2]

f    0.0
e    1.0
d    2.0
c    3.0
dtype: float64

In [5]:
a[2:]

d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [7]:
# replace the nan values
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

##### Time Series Stacking

In [72]:
data = pd.DataFrame({'year':[1959]*4, 'quarter':np.arange(1,5), 'gdp':[12000,13000,15000,18000],'unemp':[3.3,3.5,3.8,2.9]})

In [73]:
data

year  quarter    gdp  unemp
0  1959        1  12000    3.3
1  1959        2  13000    3.5
2  1959        3  15000    3.8
3  1959        4  18000    2.9

In [74]:
periods=pd.PeriodIndex(year=data.year, quarter=data.quarter, name='Qtr')
periods

PeriodIndex(['1959Q1', '1959Q2', '1959Q3', '1959Q4'], dtype='period[Q-DEC]', name='Qtr', freq='Q-DEC')

In [75]:
columns=pd.Index(['gdp','unemp'],name='item')
columns

Index(['gdp', 'unemp'], dtype='object', name='item')

In [76]:
data=data.reindex(columns=columns)
data

item    gdp  unemp
0     12000    3.3
1     13000    3.5
2     15000    3.8
3     18000    2.9

In [77]:
data.index = periods.to_timestamp('M', 'end')
data

item                             gdp  unemp
Qtr                                        
1959-03-31 23:59:59.999999999  12000    3.3
1959-06-30 23:59:59.999999999  13000    3.5
1959-09-30 23:59:59.999999999  15000    3.8
1959-12-31 23:59:59.999999999  18000    2.9

In [78]:
ldata = data.stack().reset_index().rename(columns={0: 'val'})

In [79]:
ldata

Qtr   item      val
0 1959-03-31 23:59:59.999999999    gdp  12000.0
1 1959-03-31 23:59:59.999999999  unemp      3.3
2 1959-06-30 23:59:59.999999999    gdp  13000.0
3 1959-06-30 23:59:59.999999999  unemp      3.5
4 1959-09-30 23:59:59.999999999    gdp  15000.0
5 1959-09-30 23:59:59.999999999  unemp      3.8
6 1959-12-31 23:59:59.999999999    gdp  18000.0
7 1959-12-31 23:59:59.999999999  unemp      2.9

In [81]:
pivoted = ldata.pivot('Qtr','item')
pivoted

val      
item                               gdp unemp
Qtr                                         
1959-03-31 23:59:59.999999999  12000.0   3.3
1959-06-30 23:59:59.999999999  13000.0   3.5
1959-09-30 23:59:59.999999999  15000.0   3.8
1959-12-31 23:59:59.999999999  18000.0   2.9

In [85]:
unstacked = ldata.set_index(['Qtr','item']).unstack()
unstacked

val      
item                               gdp unemp
Qtr                                         
1959-03-31 23:59:59.999999999  12000.0   3.3
1959-06-30 23:59:59.999999999  13000.0   3.5
1959-09-30 23:59:59.999999999  15000.0   3.8
1959-12-31 23:59:59.999999999  18000.0   2.9

melt

In [86]:
data = pd.DataFrame({'year':[1959]*4, 'quarter':np.arange(1,5), 'gdp':[12000,13000,15000,18000],'unemp':[3.3,3.5,3.8,2.9]})
data

year  quarter    gdp  unemp
0  1959        1  12000    3.3
1  1959        2  13000    3.5
2  1959        3  15000    3.8
3  1959        4  18000    2.9

In [88]:
data.melt(['year','quarter'])

year  quarter variable    value
0  1959        1      gdp  12000.0
1  1959        2      gdp  13000.0
2  1959        3      gdp  15000.0
3  1959        4      gdp  18000.0
4  1959        1    unemp      3.3
5  1959        2    unemp      3.5
6  1959        3    unemp      3.8
7  1959        4    unemp      2.9

***test if group objects could be transformed into dict directly***

In [12]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],'key2' : ['one', 'two', 'one', 'two', 'one'],
    'data1' : np.random.randn(5),'data2' : np.random.randn(5)})
df

key1 key2     data1     data2
0    a  one  0.320179  1.619462
1    a  two  0.010327  0.509173
2    b  one -0.864332 -0.615756
3    b  two -0.212507 -1.007946
4    a  one -0.228343 -0.720109

In [13]:
df.groupby('key1')

In [14]:
list(df.groupby('key1'))

[('a',   key1 key2     data1     data2
  0    a  one  0.320179  1.619462
  1    a  two  0.010327  0.509173
  4    a  one -0.228343 -0.720109), ('b',   key1 key2     data1     data2
  2    b  one -0.864332 -0.615756
  3    b  two -0.212507 -1.007946)]

In [9]:
pieces = dict(df.groupby('key1'))

TypeError: attribute of type 'str' is not callable

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
ts_i = pd.date_range('3/9/2012 9:30', periods=6, freq='D', tz='UTC')
ts = pd.Series(np.random.randn(len(ts_i)), index=ts_i)
ts

2012-03-09 09:30:00+00:00    1.026567
2012-03-10 09:30:00+00:00   -0.550564
2012-03-11 09:30:00+00:00    0.140840
2012-03-12 09:30:00+00:00   -0.202176
2012-03-13 09:30:00+00:00    0.175467
2012-03-14 09:30:00+00:00    1.461808
Freq: D, dtype: float64

In [11]:
ts.tz_convert('America/New_York')

2012-03-09 04:30:00-05:00    1.026567
2012-03-10 04:30:00-05:00   -0.550564
2012-03-11 05:30:00-04:00    0.140840
2012-03-12 05:30:00-04:00   -0.202176
2012-03-13 05:30:00-04:00    0.175467
2012-03-14 05:30:00-04:00    1.461808
Freq: D, dtype: float64

#### time series range

In [19]:
rng = pd.period_range('2011Q3', '2012Q4', freq='Q-JAN')
ts = pd.Series(np.arange(len(rng)), index=rng)
ts

2011Q3    0
2011Q4    1
2012Q1    2
2012Q2    3
2012Q3    4
2012Q4    5
Freq: Q-JAN, dtype: int32

In [37]:
new_rng = (rng.asfreq('B', 'e') - 1).asfreq('T', 's')+60
ts.index = new_rng.to_timestamp()
ts

2010-10-28 01:00:00    0
2011-01-28 01:00:00    1
2011-04-28 01:00:00    2
2011-07-28 01:00:00    3
2011-10-28 01:00:00    4
2012-01-30 01:00:00    5
dtype: int32

### resampling

In [40]:
rng = pd.date_range('2000-01-01', periods=12, freq='T')
ts = pd.Series(np.arange(12), index=rng)
ts

2000-01-01 00:00:00     0
2000-01-01 00:01:00     1
2000-01-01 00:02:00     2
2000-01-01 00:03:00     3
2000-01-01 00:04:00     4
2000-01-01 00:05:00     5
2000-01-01 00:06:00     6
2000-01-01 00:07:00     7
2000-01-01 00:08:00     8
2000-01-01 00:09:00     9
2000-01-01 00:10:00    10
2000-01-01 00:11:00    11
Freq: T, dtype: int32

In [41]:
ts.resample('5min', closed='left').sum()

2000-01-01 00:00:00    10
2000-01-01 00:05:00    35
2000-01-01 00:10:00    21
Freq: 5T, dtype: int32

In [42]:
ts.resample('5min', closed='right', label='right').sum()

2000-01-01 00:00:00     0
2000-01-01 00:05:00    15
2000-01-01 00:10:00    40
2000-01-01 00:15:00    11
Freq: 5T, dtype: int32

In [43]:
ts.resample('5min', closed='right', label='right', loffset='-1s').sum()

1999-12-31 23:59:59     0
2000-01-01 00:04:59    15
2000-01-01 00:09:59    40
2000-01-01 00:14:59    11
Freq: 5T, dtype: int32

In [46]:
pd.Period('2001-1')

Period('2001-01', 'M')

In [50]:
pd.period_range('2001-1',periods=10,freq='M')

PeriodIndex(['2001-01', '2001-02', '2001-03', '2001-04', '2001-05', '2001-06',
             '2001-07', '2001-08', '2001-09', '2001-10'],
            dtype='period[M]', freq='M')

### group transform

In [51]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
np.mean([0,3,6,9])

4.5

In [85]:
np.std(x[::3])

3.3541019662496847

In [86]:
pd.Series(x[::3]).std()

3.872983346207417

In [57]:
df=pd.DataFrame({'key':['a','b','c']*4, 'value':np.arange(12.)})
g=df.groupby('key').value
g.transform(lambda x: (x-x.mean())/x.std())

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [70]:
(df['value'] - g.transform('mean') )/g.transform('std')

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

#### reshape

In [7]:
arr = np.arange(10)
print(arr.shape)
arr

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr = arr.reshape(-1,1)
print(arr.shape)
arr

(10, 1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

#### array slicing`

In [2]:
arr = np.arange(30).reshape(3,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [4]:
arr[:,3]

array([ 3, 13, 23])