In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [4]:
a = tf.constant(2)
a

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [8]:
b = tf.constant([[1,2],[3,4]])
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [16]:
c = tf.Variable(3)
c.assign(4)
c.assign_add(5)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=9>

In [18]:
tf.add(3,4)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [12]:
filters = np.zeros((7,7,2,2))
filters[:,3,:,0] = 1
filters

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[1., 0.],
         [1., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[1., 0.],
         [1., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[1., 0.],
         [1., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[1., 0.],
         [1., 0